apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
# some metadata about the template itself
metadata:
  name: create-aws-s3
  title: "AWS Resource: S3"
  description: Teste de criação S3
spec:
  owner: backstage
  type: resource
  parameters:
    - title: Informações de projeto
      required: [bucket_name,owner]
      properties:
        bucket_name:
          title: Nome do Bucket
          type: string
          description: Nome do bucket
          ui:autofocus: true
        block_public:
          title: Bloquear acesso público
          type: boolean
          description: Nome do bucket
          default: true
        owner:
          title: Owner
          type: string
          description: Squad responsável
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: [Group]
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./s3
        values:
          bucket_name: ${{ parameters.bucket_name | replace(' ', '-') | replace('_', '-')}}
          block_public: ${{ parameters.block_public }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        description: add ${{ parameters.bucket_name }}
        repoUrl: github.com?owner=orgabry&repo=infra
        branchName: ${{ parameters.bucket_name }}
        title: "feat: create ${{ parameters.bucket_name }}"
        targetPath: "aws/global/${{ parameters.account }}/s3"

  output:
    links:
      - title: Ir para pull request
        url: ${{ steps.publish.output.remoteUrl }}
        icon: github